### PR TITLE
Align driver to align depth and RGB images

### PR DESCRIPTION
**Pull request by dorian3d**
It uses the implementation of libfreenect2.

### CODE REVIEW

**Comment by crheckman** [comment]
This PR is ready to be tested (and possibly merged).

**Comment by artforlife** [comment]
When testing this, we get the following error. The libuvc.h.in exists, but libuvc.h never gets generated.


```
In file included from /home/algomorph/Garage/ARPG/HAL/HAL/Camera/Drivers/RealSense/RealSense.h:6:0,
                 from /home/algomorph/Garage/ARPG/HAL/HAL/Camera/Drivers/RealSense/RealSense.cpp:1:
/home/algomorph/Garage/ARPG/HAL/HAL/Camera/Drivers/RealSense/libuvc_ex/include/libuvc_ex/libuvc.h:12:34: fatal error: libuvc/libuvc_config.h: No such file or directory
 #include <libuvc/libuvc_config.h>
                                  ^
compilation terminated.

```

**Comment by Algomorph** [comment]
[Our own fork](git@github.com:Algomorph/HAL.git) is still the only one that works (although it's a crude hack) with the latest version of the Freenect2 driver at this point. Also, it is questionable whether integration of the depth-to-RGB align driver for Freenect2 into HAL is practical at all at this point, since the Freenect2 driver now has its own depth-to-RGB registration, which is (at the time of this post) actively being improved. It may make sense to rewrite the Freenect2 HAL driver to use that instead.

**Comment by crheckman** [comment]
I agree with your proposed solution. I know you said you don't have the time to work on stuff like this, and I'm not sure of our resources to throw at it at the moment, but I'm leaning toward closing this PR and pursuing your proposed route.

As it happens, @lumark developed a software align option for the RGB and depth cams in the OpenNI driver because he wanted to be able to see for himself that the registration was valid given a rig calibration file, but it might be best if such an option lived outside of the driver and we're still sorting that out.

**Comment by crheckman** [comment]
#88 implements this and is tested, whereas this approach is stale and still causes problems after tinkering. Regardless, freenect2 apparently now supports align out of the box so we should rewrite the driver to use the new implementation and not have to use our own RGB-to-depth registration like is done here.

**Pull request closed without merging**
